services:
    webfactory_icu_translation.translator:
        decorates: translator
        class: Webfactory\IcuTranslationBundle\Translator\FormatterDecorator
        arguments: ["@webfactory_icu_translation.translator.inner", "@webfactory_icu_translation.formatter"]

    webfactory_icu_translation.formatter.intl_formatter:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\IntlFormatter

    webfactory_icu_translation.formatter.default_parameters:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\DefaultParameterDecorator
        arguments: ["@webfactory_icu_translation.formatter.intl_formatter"]

    webfactory_icu_translation.formatter.missing_parameters:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\MissingParameterWarningDecorator
        arguments: ["@webfactory_icu_translation.formatter.default_parameters", "@?logger"]
        tags:
            - { name: monolog.logger, channel: webfactory_icu_translation }

    webfactory_icu_translation.formatter.twig_parameter_normalizer:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\TwigParameterNormalizer
        arguments: ["@webfactory_icu_translation.formatter.missing_parameters"]

    webfactory_icu_translation.formatter.graceful_exceptions:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\GracefulExceptionsDecorator
        arguments: ["@webfactory_icu_translation.formatter.twig_parameter_normalizer", "@?logger"]
        tags:
            - { name: monolog.logger, channel: webfactory_icu_translation }

    webfactory_icu_translation.formatter:
        alias: webfactory_icu_translation.formatter.graceful_exceptions

    webfactory_icu_translation.twig_extension:
        class: Webfactory\IcuTranslationBundle\Twig\IcuFormattingExtension
        arguments: ["@webfactory_icu_translation.formatter.intl_formatter", "@translator"]
        tags:
            - { name: twig.extension }
