services:
    _defaults:
        autowire: true
        autoconfigure: true

    Webfactory\IcuTranslationBundle\Translator\Formatting\:
        resource: '../../Translator/Formatting/*.php'

    webfactory_icu_translation.translator:
        alias: Webfactory\IcuTranslationBundle\Translator\FormatterDecorator

    webfactory_icu_translation.formatter:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\GracefulExceptionsDecorator

    webfactory_icu_translation.formatter.intl_formatter:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\IntlFormatter
        deprecated: ~

    Webfactory\IcuTranslationBundle\Translator\Formatting\DefaultParameterDecorator:
        arguments:
            - '@Webfactory\IcuTranslationBundle\Translator\Formatting\IntlFormatter'

    webfactory_icu_translation.formatter.default_parameters:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\DefaultParameterDecorator
        deprecated: ~

    Webfactory\IcuTranslationBundle\Translator\Formatting\MissingParameterWarningDecorator:
        arguments:
            - '@Webfactory\IcuTranslationBundle\Translator\Formatting\DefaultParameterDecorator'
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: webfactory_icu_translation }

    webfactory_icu_translation.formatter.missing_parameters:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\MissingParameterWarningDecorator
        deprecated: ~

    Webfactory\IcuTranslationBundle\Translator\Formatting\TwigParameterNormalizer:
        arguments:
            - '@Webfactory\IcuTranslationBundle\Translator\Formatting\MissingParameterWarningDecorator'

    webfactory_icu_translation.formatter.twig_parameter_normalizer:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\TwigParameterNormalizer
        deprecated: ~

    Webfactory\IcuTranslationBundle\Translator\Formatting\GracefulExceptionsDecorator:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\GracefulExceptionsDecorator
        arguments:
            - '@Webfactory\IcuTranslationBundle\Translator\Formatting\TwigParameterNormalizer'
            - '@?logger'
        tags:
            - { name: monolog.logger, channel: webfactory_icu_translation }

    webfactory_icu_translation.formatter.graceful_exceptions:
        alias: Webfactory\IcuTranslationBundle\Translator\Formatting\GracefulExceptionsDecorator
        deprecated: ~

    Webfactory\IcuTranslationBundle\Translator\FormatterDecorator:
        decorates: translator
        arguments:
            - '@Webfactory\IcuTranslationBundle\Translator\FormatterDecorator.inner'
            - '@webfactory_icu_translation.formatter'
